### ISSUE TITLE
Couldn't display any syslog

### ISSUE THREAD

**Issue by Xwoder** [iMokhles/iConsole-Windows#1]
No matter that I build the project myself or download the release you provided at
```https://github.com/iMokhles/iConsole-Windows/releases```, I couldn't see any input from the window.

I am sure that I connected my device and clicked Refresh USB and Syslog buttons, but it only show that ```iOS device detected!```.

**Comment by iMokhles** [comment]
HI actually this program doesn't support iOS 10 and above you have to replace Resources folder contents with new version of every library there specially idevice***, libidevice*** and libimobile librarians
